### ISSUE TITLE
Problems with phase unwrapping results using snaphu-py

### ISSUE THREAD

**Issue by songzwgithub** [isce-framework/snaphu-py#17]
Hi,

I am using snaphu-py to unwrap interferometric phase obtained from hyp3. I am running into a couple of issues with the unwrapping results:

1. Background values seems incorrect
I notice that some background areas not covered by signal get unwrapped to incorrect phase values. 

2. Water mask does not seem to be applied
I provide a water mask raster to the snaphu.unwrap function, but this does not seem to have an effect - masked areas still get unwrapped instead of being excluded.

the command I use:
`unw, conncomp = snaphu.unwrap(igram_data, corr, nlooks=1.0, mask=mask, ntiles=(4, 4), tile_overlap=256, nproc=8)`

the wrapped phase:
![image](https://github.com/isce-framework/snaphu-py/assets/75102164/7f67e763-d890-4099-acae-ddbd1ecf48c1)
the result:
![image](https://github.com/isce-framework/snaphu-py/assets/75102164/57808939-37f2-4cd0-8247-03d1c95efcd9)
conncomp file:
![image](https://github.com/isce-framework/snaphu-py/assets/75102164/05be66bc-64e8-4d44-a454-1d77ca66c771)

I would be grateful if you could give me some advice.

**Comment by scottstanie** [comment]
Hi, thanks for testing out the code.
Your result actually looks as expected from [the SNAPHU manual](https://web.stanford.edu/group/radar/softwareandlinks/sw/snaphu/snaphu_man1.html)

> Masked areas are treated as areas in which the solution phase value is irrelevant to the solution cost.

When you supply the `BYTEMASK` to snaphu (either with `mask=` like you did here, or from `snaphu`'s command line option `−M bytemaskfile`, it just ignores those pixels and chooses whatever value is convenient for optimizing the other non-masked pixels that it cares about. This means it's common to get those block-y areas around the edges with constant or near-constant values that match some part of the real data it's touching.

I'll leave this issue open for the moment since we may consider adding an option to set the output masked value to some `nodata`. 

For your immediate purposes, you can check how I've done it here
https://github.com/isce-framework/dolphin/blob/8cfbebc082af56f96bbbe175c6e6bc252e56e5ce/src/dolphin/unwrap.py#L631-L637 where I am [creating a new temp file](https://github.com/isce-framework/dolphin/blob/8cfbebc082af56f96bbbe175c6e6bc252e56e5ce/src/dolphin/unwrap.py#L346-L364) that has zeroed out the phase and correlation of the inputs.

**Comment by gmgunter** [comment]
Just adding a bit to what @scottstanie said--

SNAPHU always assigns an unwrapped phase value to each pixel, including pixels that were masked out or too noisy to form an accurate unwrapped estimate. However, SNAPHU will set the connected component label (`conncomp` value) to 0 for pixels such as these (pixels that were masked out or that SNAPHU deemed could not be accurately unwrapped).

So, after unwrapping, you could set those unwrapped pixels to NaN (or some other "nodata" value of your choice) in order to visualize only the "valid" unwrapped pixels, e.g.

```python
unw[conncomp == 0] = np.nan
```

It seems strange to me, though, that the "background areas" (i.e. regions outside of any valid subswath) don't appear to be assigned connected component label 0 in the output `conncomp` array. If those pixels are filled with NaN values, then we should be treating them as masked out. There's a unit test that specifically checks this behavior:

https://github.com/isce-framework/snaphu-py/blob/e262d2f42918d0a3b2073871f8f90ca5900b482f/test/test_unwrap.py#L55

@songzwgithub what is the `igram_data` value of pixels in the background area around the border?

**Comment by songzwgithub** [comment]
> 只是添加一点什么@scottstanie说 -
> 
> SNAPHU 始终为每个像素分配一个展开相位值，包括被屏蔽或噪声太大而无法形成准确的展开估计的像素。`conncomp`但是，对于此类像素（被屏蔽或 SNAPHU 认为无法准确展开的像素），SNAPHU 会将连接组件标签（值）设置为 0。
> 
> 因此，展开后，您可以将这些展开的像素设置为 NaN（或您选择的其他“nodata”值），以便仅可视化“有效”展开的像素，例如
> 
> ```python
> unw[conncomp == 0] = np.nan
> ```
> 
> 不过，对我来说，“背景区域”（即任何有效子带之外的区域）似乎没有在输出数组中分配连接组件标签 0，这似乎很奇怪`conncomp`。如果这些像素填充有 NaN 值，那么我们应该将它们视为被屏蔽。有一个单元测试专门检查此行为：
> 
> https://github.com/isce-framework/snaphu-py/blob/e262d2f42918d0a3b2073871f8f90ca5900b482f/test/test_unwrap.py#L55
> 
> @songzwgithub`igram_data`边框周围背景区域的像素值是多少？

Thank you for your reply.
I've noticed that using either `igram_data[mask == 0] = np.nan` or `igram_data[corr < 0.3] = np.nan` before unwrapping seems to work. Is that right?

In the background area around the border, the pixel values of `igram_data` are `0.0000`. However, the unwrapped phase values in the same background area are `0, 6.28315..., -6.28315..., 12.5663..., -12.5663..., 18.8495..., -18.8495..., 25.1327..., -25.1327..., etc.` The values appear to be related to multiples of 2π, but not exact multiples.

**Comment by songzwgithub** [comment]
> Hi, thanks for testing out the code. Your result actually looks as expected from [the SNAPHU manual](https://web.stanford.edu/group/radar/softwareandlinks/sw/snaphu/snaphu_man1.html)
> 
> > Masked areas are treated as areas in which the solution phase value is irrelevant to the solution cost.
> 
> When you supply the `BYTEMASK` to snaphu (either with `mask=` like you did here, or from `snaphu`'s command line option `−M bytemaskfile`, it just ignores those pixels and chooses whatever value is convenient for optimizing the other non-masked pixels that it cares about. This means it's common to get those block-y areas around the edges with constant or near-constant values that match some part of the real data it's touching.
> 
> I'll leave this issue open for the moment since we may consider adding an option to set the output masked value to some `nodata`.
> 
> For your immediate purposes, you can check how I've done it here https://github.com/isce-framework/dolphin/blob/8cfbebc082af56f96bbbe175c6e6bc252e56e5ce/src/dolphin/unwrap.py#L631-L637 where I am [creating a new temp file](https://github.com/isce-framework/dolphin/blob/8cfbebc082af56f96bbbe175c6e6bc252e56e5ce/src/dolphin/unwrap.py#L346-L364) that has zeroed out the phase and correlation of the inputs.

Thanks for the suggestion, I will try this and look forward to the code update.

**Comment by gmgunter** [comment]
>I've noticed that using either `igram_data[mask == 0] = np.nan` or `igram_data[corr < 0.3] = np.nan` before unwrapping seems to work. Is that right?

In snaphu-py, we treat NaN-valued interferogram pixels as though they had zero-magnitude.

https://github.com/isce-framework/snaphu-py/blob/e262d2f42918d0a3b2073871f8f90ca5900b482f/src/snaphu/_unwrap.py#L474-L475

As far as SNAPHU is concerned, pixels that are masked out and pixels with zero magnitude are functionally the same thing.

>```
>  The user can indicate masking by setting the magnitudes of the
>  complex values of pixels to be masked to zero in the input file or
>  by specifying a separate binary mask via the new -M option or the
>  new BYTEMASKFILE keyword.
>```

https://github.com/gmgunter/snaphu/blob/4b7ca6c08eec6b7e6a61d739237b8c182f0ce795/README_releasenotes.txt#L71-L78

So I think setting `igram_data[mask == 0] = np.nan` is unlikely to have any useful effect -- those pixels are already masked out.

On the other hand, masking out low-coherence pixels by setting (for example) `igram_data[corr < 0.3] = np.nan` is a common practice that may improve unwrapping runtime and accuracy.

However, I don't see that either of those strategies could resolve your original issue of masking out invalid pixels in the output unwrapped phase array. As we've established, SNAPHU always assigns an unwrapped phase value to each pixel in the output array, even masked out pixels. So setting input interferogram pixels to NaN won't help with that -- you would still need to apply a mask to the output unwrapped phase array after unwrapping.

>In the background area around the border, the pixel values of `igram_data` are `0.0000`.

Hmm, that's surprising to me. I would expect those pixels to then be set to 0 in the output `conncomp` array. Maybe a bug? I'll see if I can reproduce some similar behavior.

It might just be due to floating-point imprecision. It looks like SNAPHU only treats pixels as masked out if their magnitude is *exactly* zero.

> ```c
>   /* set weights to zero for arcs adjacent to zero-magnitude pixels */
>   if(mag!=NULL){
>     for(row=0;row<nrow;row++){
>       for(col=0;col<ncol;col++){
>         if(mag[row][col]==0){
>           if(row>0){
>             rowweight[row-1][col]=0;
>           }
>           if(row<nrow-1){
>             rowweight[row][col]=0;
>           }
>           if(col>0){
>             colweight[row][col-1]=0;
>           }
>           if(col<ncol-1){
>             colweight[row][col]=0;
>           }
>         }
>       }
>     }
>   }
> ```

https://github.com/gmgunter/snaphu/blob/4b7ca6c08eec6b7e6a61d739237b8c182f0ce795/src/snaphu_cost.c#L171-L191

>However, the unwrapped phase values in the same background area are `0, 6.28315..., -6.28315..., 12.5663..., -12.5663..., 18.8495..., -18.8495..., 25.1327..., -25.1327..., etc.` The values appear to be related to multiples of 2π, but not exact multiples.

FYI, I believe the reason that the unwrapped values are close-but-not-quite exact multiples of $2\pi$ is because the way that SNAPHU computes the final unwrapped phase is susceptible to large accumulated floating-point rounding errors. We patched this in ISCE3 a while back, but so far I've been too lazy to submit the patch upstream to SNAPHU's author. More details here: https://github.com/isce-framework/isce3/commit/fe6cba72eeba8f58cd4bf5d24ca8ff306e2ffe13

**Comment by songzwgithub** [comment]
> > I've noticed that using either `igram_data[mask == 0] = np.nan` or `igram_data[corr < 0.3] = np.nan` before unwrapping seems to work. Is that right?
> 
> In snaphu-py, we treat NaN-valued interferogram pixels as though they had zero-magnitude.
> 
> https://github.com/isce-framework/snaphu-py/blob/e262d2f42918d0a3b2073871f8f90ca5900b482f/src/snaphu/_unwrap.py#L474-L475
> 
> As far as SNAPHU is concerned, pixels that are masked out and pixels with zero magnitude are functionally the same thing.
> 
> > ```
> >  The user can indicate masking by setting the magnitudes of the
> >  complex values of pixels to be masked to zero in the input file or
> >  by specifying a separate binary mask via the new -M option or the
> >  new BYTEMASKFILE keyword.
> > ```
> 
> https://github.com/gmgunter/snaphu/blob/4b7ca6c08eec6b7e6a61d739237b8c182f0ce795/README_releasenotes.txt#L71-L78
> 
> So I think setting `igram_data[mask == 0] = np.nan` is unlikely to have any useful effect -- those pixels are already masked out.
> 
> On the other hand, masking out low-coherence pixels by setting (for example) `igram_data[corr < 0.3] = np.nan` is a common practice that may improve unwrapping runtime and accuracy.
> 
> However, I don't see that either of those strategies could resolve your original issue of masking out invalid pixels in the output unwrapped phase array. As we've established, SNAPHU always assigns an unwrapped phase value to each pixel in the output array, even masked out pixels. So setting input interferogram pixels to NaN won't help with that -- you would still need to apply a mask to the output unwrapped phase array after unwrapping.
> 
> > In the background area around the border, the pixel values of `igram_data` are `0.0000`.
> 
> Hmm, that's surprising to me. I would expect those pixels to then be set to 0 in the output `conncomp` array. Maybe a bug? I'll see if I can reproduce some similar behavior.
> 
> It might just be due to floating-point imprecision. It looks like SNAPHU only treats pixels as masked out if their magnitude is _exactly_ zero.
> 
> > ```c
> >   /* set weights to zero for arcs adjacent to zero-magnitude pixels */
> >   if(mag!=NULL){
> >     for(row=0;row<nrow;row++){
> >       for(col=0;col<ncol;col++){
> >         if(mag[row][col]==0){
> >           if(row>0){
> >             rowweight[row-1][col]=0;
> >           }
> >           if(row<nrow-1){
> >             rowweight[row][col]=0;
> >           }
> >           if(col>0){
> >             colweight[row][col-1]=0;
> >           }
> >           if(col<ncol-1){
> >             colweight[row][col]=0;
> >           }
> >         }
> >       }
> >     }
> >   }
> > ```
> 
> https://github.com/gmgunter/snaphu/blob/4b7ca6c08eec6b7e6a61d739237b8c182f0ce795/src/snaphu_cost.c#L171-L191
> 
> > However, the unwrapped phase values in the same background area are `0, 6.28315..., -6.28315..., 12.5663..., -12.5663..., 18.8495..., -18.8495..., 25.1327..., -25.1327..., etc.` The values appear to be related to multiples of 2π, but not exact multiples.
> 
> FYI, I believe the reason that the unwrapped values are close-but-not-quite exact multiples of 2π is because the way that SNAPHU computes the final unwrapped phase is susceptible to large accumulated floating-point rounding errors. We patched this in ISCE3 a while back, but so far I've been too lazy to submit the patch upstream to SNAPHU's author. More details here: https://github.com/isce-framework/isce3/commit/fe6cba72eeba8f58cd4bf5d24ca8ff306e2ffe13


Thanks,

I get the expected result using `unw[np.isnan(igram_data)] = np.nan`. But does using `igram_data[mask == 0] = np.nan` get different results. Here are the results:

Using `igram_data[mask == 0] = np.nan`:
![image](https://github.com/isce-framework/snaphu-py/assets/75102164/9a2a9811-cb0a-4953-9b19-24fff1479667)

Without `igram_data[mask == 0] = np.nan`：
![image](https://github.com/isce-framework/snaphu-py/assets/75102164/54778357-de6e-4079-b93e-cf2c1536e5d8)

The code I use:
```
    with rasterio.open(corr_path[0]) as corr_src:
        corr = corr_src.read(1)

    with rasterio.open(mask_path[0]) as mask_src:
        mask = mask_src.read(1)

    with rasterio.open(igram_path[0]) as igram_src:
        igram_data = igram_src.read(1)  #
        igram_data[igram_data == 0] = np.nan
        igram_data[mask == 0] = np.nan
        #igram_data[corr < 0.3] = np.nan
        igram = np.exp(1j * igram_data)


    unw, conncomp = snaphu.unwrap(igram, corr, nlooks=5.0, mask=mask, ntiles=(4, 4), tile_overlap=256, nproc=32)

    unw[np.isnan(igram_data)] = np.nan

 
```

**Comment by gmgunter** [comment]
Aren't the two results simply different because of the last line in your snippet?

```python
unw[np.isnan(igram_data)] = np.nan
```

This is checking which pixels were NaN in the input interferogram and setting those same pixels to NaN in the output unwrapped phase. Therefore, setting `igram_data[mask == 0] = np.nan` prior to unwrapping is ultimately resulting in those pixels being set to NaN in the `unw` array as well. Presumably, the results are identical apart from the masked pixels.

One more thing--

This line:

```python
igram = np.exp(1j * igram_data)
```

is telling me that `igram_data` is actually the interferometric phase, rather than the complex-valued interferogram. That explains why the background area was not automatically masked out by the algorithm. Zero phase and zero magnitude are two different things. SNAPHU masks out zero-magnitude pixels because the phase information of such pixels is not meaningful. But it intentionally does not try to mask out pixels whose phase is zero, because valid pixels may have phase equal to zero.

Therefore, this is probably not a good idea:

```python
igram_data[igram_data == 0] = np.nan
```

because you might accidentally mask out some valid data that happened to have zero phase.

Instead, I expect that you could just mask out the background areas (without accidentally masking out any valid data) using the coherence data like this:

```python
igram_data[corr == 0.0] = np.nan
```

since presumably the background pixels have a coherence of zero. The sample coherence by definition cannot be zero-valued for valid pixels, so there should be no danger of accidentally masking out any real data with this approach.

**Comment by songzwgithub** [comment]
It was a misunderstanding on my part and I have modified the code. The above processing was done because the interferometric phase obtained from hyp3 is in real form. 
Thanks a lot!

**Comment by gmgunter** [comment]
You're welcome!

**Comment by aihui1104** [comment]
hello,
I noticed that you were interested in InSAR inversion of soil moisture before, could you please share with me? Could you give me your email? My email is aihui@mail.hnust.edu.cn, looking forward to receiving your email.
Kind regards,
Hui Ai
